# Generated by Django 2.1a1 on 2018-05-23 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('hukbun', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('jumin', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=10)),
                ('variance', models.CharField(max_length=10)),
                ('gradeCredit', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('advisor', models.CharField(max_length=10)),
                ('compleSemester', models.CharField(max_length=3)),
                ('earlyGradu', models.CharField(max_length=1)),
                ('admission', models.DateField()),
                ('enginCertifi', models.CharField(max_length=20)),
                ('is_anonymous', models.BooleanField()),
                ('is_authenticated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('subjectCode', models.CharField(max_length=15)),
                ('subjectName', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.IntegerField()),
                ('eisu', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField()),
                ('professor', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('lectureRoom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eisu', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=50, null=True)),
                ('yearNsemester', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_design', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('valid', models.CharField(blank=True, max_length=50, null=True)),
                ('hukbun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHopeCareers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careers', models.CharField(blank=True, max_length=50, null=True)),
                ('ranking', models.IntegerField()),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('Enterprise', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('hukbun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
