# Generated by Django 2.0.2 on 2018-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=15)),
                ('semester', models.CharField(max_length=15)),
                ('subjectCode', models.CharField(max_length=15)),
                ('subjectName', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('eisu', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('professor', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('lectureRoom', models.CharField(blank=True, max_length=100, null=True)),
                ('huksu_code', models.CharField(blank=True, max_length=50, null=True)),
                ('course_time', models.CharField(blank=True, max_length=15, null=True)),
                ('design_score', models.CharField(blank=True, default='0', max_length=15, null=True)),
                ('desription', models.CharField(blank=True, max_length=1000, null=True)),
                ('Knowledge_application', models.CharField(blank=True, max_length=5, null=True)),
                ('verification_ability', models.CharField(blank=True, max_length=5, null=True)),
                ('problem_solving', models.CharField(blank=True, max_length=5, null=True)),
                ('tool_utilization', models.CharField(blank=True, max_length=5, null=True)),
                ('design_ability', models.CharField(blank=True, max_length=5, null=True)),
                ('teamwork_skill', models.CharField(blank=True, max_length=5, null=True)),
                ('communication', models.CharField(blank=True, max_length=5, null=True)),
                ('understanding_of_influence', models.CharField(blank=True, max_length=5, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=5, null=True)),
                ('self_led', models.CharField(blank=True, max_length=5, null=True)),
                ('Lecture_type', models.CharField(blank=True, max_length=100, null=True)),
                ('teaching_method', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('Assignment', models.CharField(blank=True, max_length=500, null=True)),
                ('Midterm_exam', models.CharField(blank=True, max_length=10, null=True)),
                ('final_exam', models.CharField(blank=True, max_length=10, null=True)),
                ('attendance', models.CharField(blank=True, max_length=10, null=True)),
                ('assignments_and_others', models.CharField(blank=True, max_length=10, null=True)),
                ('grading_division', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_publication', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
